      - name: Trigger monitor run
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
        run: |
          curl -s -X POST "https://api.getpostman.com/monitors/1f087cde-8b0e-4d40-bf0f-7941bfe55d4c/run" \
            -H "X-Api-Key: $POSTMAN_API_KEY" \
            -o artifacts/monitor_trigger.json

          echo "Monitor trigger response:"
          cat artifacts/monitor_trigger.json
